### ISSUE TITLE
Running HabaneroUPC++ Programs with mpirun with -np more than 1 crashes all the time.

### ISSUE THREAD

**Issue by NecOnIce** [habanero-rice/habanero-upc#1]
Hi,

i have tried to run some Programs with HabaneroUPC++ and mpirun. But if i set mpirun -np to more than 1, e.g. -np 2 or -np 4, the Program always crashes after the hupcpp::launch Method is invoked.

The Message:

/usr/bin/mpirun -np 2 ./HelloHabaneroUPC
**\* Caught a fatal signal: SIGSEGV(11) on node 0/2
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 

Here is one simple test program:

```
int main(int argc, char **argv) {

    hupcpp::launch(&argc, &argv, [=] () {

        hupcpp::finish_spmd([=] () {

            cout << "Number of Workers: " << hupcpp::numWorkers() << endl;

            for (int i = 0; i < 100; i++) {
                hupcpp::async([=] () {
                    int temp = 0;
                    for (int j = 0; j < 10000; j++) {
                        temp++;
                        temp += 2;
                    }
                   cout << "Hello, i'm worker " << hupcpp::get_hc_wid() << " !" << endl;
                });
            }
        });
    });

    cout << "Program terminating." << endl;
    return 0;
}
```

The example Programs of upcxx are working all fine... only HabaneroUPC++ Programs fail.

**Comment by vkaries** [comment]
Hi NecOnlce,

Yes, we are aware of this bug and we are working to get it resolved. Will mail you back once its resolved.

Thanks
Vivek Kumar

**Comment by vkaries** [comment]
Hi NecOnlce,

Can you please do a git pull on habanero-upc and retry after building the repo? A fix to the segfault has recently been pushed. Please let us know if you still face the issue.

Thanks
Vivek

**Comment by vivkumar** [comment]
Hi NecOnlce,

Sorry, I guess you have to wait for some more time as we found some more issues. Will let you know once everything is set.

Thanks
Vivek

**Comment by NecOnIce** [comment]
Hi Vivek,

i have done a complete git pull. It seems that all is working fine at the Moment. I'm now able to run the Programs with mpirun with more than 1 node. What kind of Bugs do you have discovered in addition ?

Thanks
NecOnIce

**Comment by agrippa** [comment]
@NecOnIce There was an issue with how some UPCXX shared locks were being initialized inside the Habanero-UPC++ runtime and with dynamic linking of the Habanero-UPC++ library. I believe the fixes Vivek refers to are in the following commit:

https://github.com/habanero-rice/habanero-upc/commit/04f25e7bc4a0cded7415ff1ba055375e02a6ddd0

This issue was not present on the clusters we were using earlier to test Habanero-UPC++ but manifested themselves only when we started experimenting on some new clusters. Is this issue close-able?

**Comment by NecOnIce** [comment]
Sry for my very late response! 

This Issue was resolved by the last commit mentioned above.
